name: Run tests and verify code
on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup npm registry
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Enable corepack
        shell: bash
        run: corepack enable

      - name: Install packages
        run: yarn --immutable

      - name: Run tests
        run: yarn test:ci

      - name: Run typecheck
        run: yarn typecheck

      - name: Run linter
        run: yarn lint:ci
